#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)
#ifndef UBGEAR_SWIFT_H
#define UBGEAR_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AWSCognitoIdentityProvider;
@import AWSCore;
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="UBGear",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


@class NSNumber;
@class NSURL;
@class NSString;
@class NSDate;
@class NSData;
@class UIImage;

SWIFT_CLASS("_TtC6UBGear12CacheManager")
@interface CacheManager : NSObject
+ (void)executeManagingStroage;
+ (double)sizeOfCachedStorage SWIFT_WARN_UNUSED_RESULT;
+ (NSURL * _Nullable)oldestAsset SWIFT_WARN_UNUSED_RESULT;
+ (NSURL * _Nullable)findFigureWithUuid:(NSString * _Nonnull)uuid updateDate:(NSDate * _Nullable)updateDate SWIFT_WARN_UNUSED_RESULT;
+ (void)storeItemAsDaeiWithUuid:(NSString * _Nonnull)uuid data:(NSData * _Nonnull)data eTag:(NSString * _Nonnull)eTag completion:(SWIFT_NOESCAPE void (^ _Nonnull)(BOOL, NSError * _Nullable))completion;
+ (void)createCacheDirectoryIfNeeded;
+ (void)deleteDirectoryIfNeededWithDirectory:(NSURL * _Nonnull)directory;
+ (void)deleteOldestItemWithCompletion:(void (^ _Nullable)(BOOL, NSString * _Nonnull))completion;
+ (void)deleteItemAt:(NSURL * _Nonnull)url completion:(SWIFT_NOESCAPE void (^ _Nonnull)(BOOL, NSString * _Nonnull))completion;
+ (void)deleteItemWithUuid:(NSString * _Nonnull)uuid completion:(SWIFT_NOESCAPE void (^ _Nonnull)(BOOL, NSString * _Nonnull))completion;
+ (void)deleteAllItemWithCompletion:(SWIFT_NOESCAPE void (^ _Nonnull)(BOOL, NSString * _Nonnull))completion;
+ (UIImage * _Nullable)getMaterialImageWithPath:(NSString * _Nonnull)path SWIFT_WARN_UNUSED_RESULT;
+ (void)saveMaterialImage:(UIImage * _Nonnull)image key:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, CategoryType, open) {
  CategoryTypeArchitecture = 0,
  CategoryTypeProduct = 1,
  CategoryTypeFinishes = 2,
  CategoryTypeMigrations = 3,
  CategoryTypeSpatial = 4,
};

typedef SWIFT_ENUM(NSInteger, InteriorStyle, open) {
  InteriorStyleCasual = 0,
  InteriorStyleClassic = 1,
  InteriorStyleModern = 2,
  InteriorStyleNatural = 3,
  InteriorStyleNordic = 4,
  InteriorStyleRomantic = 5,
  InteriorStyleVintage = 6,
};


@class NSDictionary;

SWIFT_CLASS("_TtC6UBGear15SpaceClassifier")
@interface SpaceClassifier : NSObject
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic) CGFloat percent;
- (nonnull instancetype)initWith:(NSDictionary * _Nonnull)result OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nonnull)percentToString SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC6UBGear10SpaceColor")
@interface SpaceColor : NSObject
@property (nonatomic) CGFloat red;
@property (nonatomic) CGFloat green;
@property (nonatomic) CGFloat blue;
@property (nonatomic) double percent;
- (nonnull instancetype)initWith:(NSDictionary * _Nonnull)result OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC6UBGear20SpaceObjectDetection")
@interface SpaceObjectDetection : NSObject
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic) CGFloat percent;
@property (nonatomic) CGRect rect;
- (nonnull instancetype)initWith:(NSDictionary * _Nonnull)result OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nonnull)percentToString SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC6UBGear10SpaceStyle")
@interface SpaceStyle : NSObject
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic) CGFloat percent;
@property (nonatomic, copy) NSString * _Nonnull styleDescription;
- (nonnull instancetype)initWith:(NSDictionary * _Nonnull)result OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nonnull)percentToString SWIFT_WARN_UNUSED_RESULT;
@end

@class UBLikeInfo;

SWIFT_PROTOCOL("_TtP6UBGear14UBLikeProtocol_") SWIFT_AVAILABILITY(ios,introduced=11.3)
@protocol UBLikeProtocol
@property (nonatomic, strong) UBLikeInfo * _Nullable likeInfo;
- (void)setLikeInformationWith:(UBLikeInfo * _Nonnull)like;
@end

@class UBStyle;

/// A informative class that manages properties of figure.
SWIFT_CLASS("_TtC6UBGear7UBAsset") SWIFT_AVAILABILITY(ios,introduced=11.3)
@interface UBAsset : NSObject <UBLikeProtocol>
@property (nonatomic, strong) UBLikeInfo * _Nullable likeInfo;
/// The <code>UUID</code> of <code>UBAsset</code>
@property (nonatomic, readonly, copy) NSString * _Nonnull asset_id;
@property (nonatomic, readonly, copy) NSString * _Nonnull title;
/// A brand name of asset
@property (nonatomic, readonly, copy) NSString * _Nonnull brand;
@property (nonatomic, readonly, copy) NSString * _Nonnull thumbnail_path;
/// A <code>Boolean</code> value indicating whether the user likes it.
@property (nonatomic) BOOL isLike;
/// An array of <code>UBStyle</code>
@property (nonatomic, copy) NSArray<UBStyle *> * _Nonnull styles;
@property (nonatomic, readonly, copy) NSString * _Nonnull asset_description;
- (void)setLikeInformationWith:(UBLikeInfo * _Nonnull)like;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// A informative class that represents the figure’s apperance.
SWIFT_CLASS("_TtCC6UBGear7UBAsset7UBStyle")
@interface UBStyle : NSObject
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nonnull asset_id;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic) BOOL enabled;
@property (nonatomic) BOOL is_default;
@property (nonatomic, copy) NSString * _Nonnull thumbnail_path;
@property (nonatomic, copy) NSDate * _Nonnull created_date;
@property (nonatomic, copy) NSDate * _Nonnull updated_date;
@property (nonatomic, copy) NSDate * _Nonnull deleted_date;
/// A  <code>URL</code> path of color chip image
@property (nonatomic, copy) NSString * _Nonnull color_chip_path;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC6UBGear10UBAssetSet") SWIFT_AVAILABILITY(ios,introduced=11.3)
@interface UBAssetSet : NSObject
@property (nonatomic, copy) NSString * _Nonnull title;
@property (nonatomic) BOOL enabled;
@property (nonatomic) BOOL publish;
@property (nonatomic, copy) NSString * _Nonnull thumbnail_path;
@property (nonatomic, copy) NSArray<UBAsset *> * _Nonnull assets;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UBResponse;
@class UIViewController;

SWIFT_CLASS("_TtC6UBGear6UBAuth") SWIFT_AVAILABILITY(ios,introduced=11.3)
@interface UBAuth : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable currentToken;
- (void)configureWithCliendId:(NSString * _Nonnull)cliendId clientSecret:(NSString * _Nonnull)clientSecret poolId:(NSString * _Nonnull)poolId webDomain:(NSString * _Nonnull)webDomain appscheme:(NSString * _Nonnull)appscheme;
- (void)updateCurrentUser;
- (void)signInEmail:(NSString * _Nonnull)email password:(NSString * _Nonnull)password completion:(void (^ _Nonnull)(UBResponse * _Nonnull))completion;
- (void)signOut;
/// 회원 탈퇴하기
- (void)leaveWithUserId:(NSString * _Nonnull)userId completion:(void (^ _Nonnull)(UBResponse * _Nonnull))completion;
- (void)changePasswordWithCurrent:(NSString * _Nonnull)current new:(NSString * _Nonnull)new_ completion:(void (^ _Nonnull)(UBResponse * _Nonnull))completion;
- (void)forgotPasswordWithUserName:(NSString * _Nonnull)userName completion:(void (^ _Nonnull)(UBResponse * _Nonnull))completion;
- (void)resendConfirmationLinkWithUserName:(NSString * _Nonnull)userName completion:(void (^ _Nonnull)(UBResponse * _Nonnull))completion;
- (BOOL)isLoggedIn SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isSignedInCognito SWIFT_WARN_UNUSED_RESULT;
- (void)startSignInFlowWithViewController:(UIViewController * _Nonnull)viewController;
- (BOOL)isValidEmail:(NSString * _Nonnull)email SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isValidPassword:(NSString * _Nonnull)password SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol AWSCognitoIdentityPasswordAuthentication;

SWIFT_AVAILABILITY(ios,introduced=11.3)
@interface UBAuth (SWIFT_EXTENSION(UBGear)) <AWSCognitoIdentityInteractiveAuthenticationDelegate>
- (id <AWSCognitoIdentityPasswordAuthentication> _Nonnull)startPasswordAuthentication SWIFT_WARN_UNUSED_RESULT;
@end

@class AWSCognitoIdentityPasswordAuthenticationInput;
@class AWSCognitoIdentityPasswordAuthenticationDetails;

SWIFT_AVAILABILITY(ios,introduced=11.3)
@interface UBAuth (SWIFT_EXTENSION(UBGear)) <AWSCognitoIdentityPasswordAuthentication>
- (void)getPasswordAuthenticationDetails:(AWSCognitoIdentityPasswordAuthenticationInput * _Nonnull)authenticationInput passwordAuthenticationCompletionSource:(AWSTaskCompletionSource<AWSCognitoIdentityPasswordAuthenticationDetails *> * _Nonnull)passwordAuthenticationCompletionSource;
- (void)didCompletePasswordAuthenticationStepWithError:(NSError * _Nullable)error;
@end

@class UBMaterial;

SWIFT_CLASS("_TtC6UBGear10UBCategory") SWIFT_AVAILABILITY(ios,introduced=11.3)
@interface UBCategory : NSObject
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic) BOOL is_default;
@property (nonatomic) BOOL enabled;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull thumbnail_path;
@property (nonatomic, copy) NSString * _Nonnull parent_id;
@property (nonatomic, copy) NSString * _Nonnull path;
@property (nonatomic) NSInteger depth;
@property (nonatomic) NSInteger sort;
@property (nonatomic, copy) NSString * _Nonnull code;
@property (nonatomic, copy) NSArray<UBCategory *> * _Nonnull subcategories;
@property (nonatomic) BOOL is_endpoint;
@property (nonatomic, copy) NSArray<UBAsset *> * _Nonnull assets;
@property (nonatomic, copy) NSString * _Nonnull english;
@property (nonatomic, copy) NSString * _Nonnull korean;
@property (nonatomic, copy) NSString * _Nonnull japanese;
- (nonnull instancetype)initWithResponse:(NSDictionary * _Nonnull)response OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWith:(NSString * _Nonnull)jsonString OBJC_DESIGNATED_INITIALIZER;
+ (void)requestCategoriesWithType:(enum CategoryType)type completion:(void (^ _Nonnull)(UBResponse * _Nonnull, UBCategory * _Nullable))completion;
+ (void)requestSearchCategoryWithCompletion:(void (^ _Nonnull)(UBResponse * _Nonnull, NSArray<UBCategory *> * _Nullable))completion;
+ (void)requestFlattendCategoriesWithType:(enum CategoryType)type completion:(void (^ _Nonnull)(UBResponse * _Nonnull, NSArray<UBCategory *> * _Nullable))completion;
+ (void)requestMaterialsWithCategory:(UBCategory * _Nonnull)category limit:(NSInteger)limit offset:(NSInteger)offset userEmail:(NSString * _Nonnull)userEmail completion:(void (^ _Nonnull)(UBResponse * _Nonnull, NSArray<UBMaterial *> * _Nullable))completion;
+ (void)requestAutoCompletionWithKeyword:(NSString * _Nonnull)keyword count:(NSInteger)count completion:(void (^ _Nonnull)(UBResponse * _Nonnull, NSArray<UBCategory *> * _Nullable))completion;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC6UBGear10UBLikeInfo") SWIFT_AVAILABILITY(ios,introduced=11.3)
@interface UBLikeInfo : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC6UBGear10UBMaterial") SWIFT_AVAILABILITY(ios,introduced=11.3)
@interface UBMaterial : NSObject <UBLikeProtocol>
@property (nonatomic, copy) NSString * _Nonnull geometry;
@property (nonatomic, copy) NSString * _Nonnull material_id;
@property (nonatomic, copy) NSString * _Nonnull thumbnail_path;
@property (nonatomic, strong) NSDictionary * _Nonnull responseData;
@property (nonatomic, copy) NSString * _Nonnull title;
@property (nonatomic, copy) NSString * _Nonnull materialDescription;
@property (nonatomic, readonly, copy) NSString * _Nonnull brand;
@property (nonatomic, strong) UBLikeInfo * _Nullable likeInfo;
@property (nonatomic) BOOL isLike;
- (nonnull instancetype)initWith:(NSDictionary * _Nonnull)response OBJC_DESIGNATED_INITIALIZER;
- (void)setLikeInformationWith:(UBLikeInfo * _Nonnull)like;
+ (void)requestMaterialDetailWithMaterialId:(NSString * _Nonnull)materialId userEmail:(NSString * _Nonnull)userEmail completion:(void (^ _Nonnull)(UBResponse * _Nonnull, UBMaterial * _Nullable))completion;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC6UBGear10UBResponse")
@interface UBResponse : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable result;
@property (nonatomic, readonly, strong) NSDictionary * _Nullable responseData;
@property (nonatomic, readonly, copy) NSString * _Nullable message;
- (nonnull instancetype)initWithResponseObject:(id _Nonnull)responseObject OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithError:(NSError * _Nonnull)error OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithResult:(NSString * _Nonnull)result message:(NSString * _Nonnull)message data:(NSDictionary * _Nullable)data OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface UBResponse (SWIFT_EXTENSION(UBGear))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UBResponse * _Nonnull success;)
+ (UBResponse * _Nonnull)success SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) BOOL isSuccess;
@end


SWIFT_CLASS("_TtC6UBGear13UBSpaceResult") SWIFT_AVAILABILITY(ios,introduced=11.3)
@interface UBSpaceResult : NSObject <UBLikeProtocol>
@property (nonatomic, strong) NSDictionary * _Nonnull data;
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, copy) NSString * _Nonnull user_id;
@property (nonatomic, copy) NSDate * _Nullable createDate;
@property (nonatomic, copy) NSDate * _Nullable deletedDate;
@property (nonatomic, copy) NSString * _Nonnull title;
@property (nonatomic) BOOL isPublic;
@property (nonatomic, copy) NSString * _Nonnull image_path;
@property (nonatomic) CGSize image_size;
@property (nonatomic, copy) NSString * _Nonnull profile;
@property (nonatomic, copy) NSString * _Nonnull username;
@property (nonatomic, copy) NSArray<SpaceClassifier *> * _Nonnull classifier_result;
@property (nonatomic, copy) NSArray<SpaceObjectDetection *> * _Nonnull detector_result;
@property (nonatomic, copy) NSArray<SpaceStyle *> * _Nonnull style_result;
@property (nonatomic, copy) NSArray<SpaceColor *> * _Nonnull color_result;
@property (nonatomic, readonly, strong) SpaceClassifier * _Nonnull mainRoomType;
@property (nonatomic, readonly, strong) SpaceStyle * _Nonnull mainStyle;
@property (nonatomic, strong) UBLikeInfo * _Nullable likeInfo;
@property (nonatomic) BOOL isLike;
@property (nonatomic, readonly) BOOL isDeleted;
- (nonnull instancetype)initWith:(NSDictionary * _Nonnull)data OBJC_DESIGNATED_INITIALIZER;
- (void)setLikeInformationWith:(UBLikeInfo * _Nonnull)like;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__ARM_ARCH_7S__) && __ARM_ARCH_7S__
// Generated by Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)
#ifndef UBGEAR_SWIFT_H
#define UBGEAR_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AWSCognitoIdentityProvider;
@import AWSCore;
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="UBGear",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


@class NSNumber;
@class NSURL;
@class NSString;
@class NSDate;
@class NSData;
@class UIImage;

SWIFT_CLASS("_TtC6UBGear12CacheManager")
@interface CacheManager : NSObject
+ (void)executeManagingStroage;
+ (double)sizeOfCachedStorage SWIFT_WARN_UNUSED_RESULT;
+ (NSURL * _Nullable)oldestAsset SWIFT_WARN_UNUSED_RESULT;
+ (NSURL * _Nullable)findFigureWithUuid:(NSString * _Nonnull)uuid updateDate:(NSDate * _Nullable)updateDate SWIFT_WARN_UNUSED_RESULT;
+ (void)storeItemAsDaeiWithUuid:(NSString * _Nonnull)uuid data:(NSData * _Nonnull)data eTag:(NSString * _Nonnull)eTag completion:(SWIFT_NOESCAPE void (^ _Nonnull)(BOOL, NSError * _Nullable))completion;
+ (void)createCacheDirectoryIfNeeded;
+ (void)deleteDirectoryIfNeededWithDirectory:(NSURL * _Nonnull)directory;
+ (void)deleteOldestItemWithCompletion:(void (^ _Nullable)(BOOL, NSString * _Nonnull))completion;
+ (void)deleteItemAt:(NSURL * _Nonnull)url completion:(SWIFT_NOESCAPE void (^ _Nonnull)(BOOL, NSString * _Nonnull))completion;
+ (void)deleteItemWithUuid:(NSString * _Nonnull)uuid completion:(SWIFT_NOESCAPE void (^ _Nonnull)(BOOL, NSString * _Nonnull))completion;
+ (void)deleteAllItemWithCompletion:(SWIFT_NOESCAPE void (^ _Nonnull)(BOOL, NSString * _Nonnull))completion;
+ (UIImage * _Nullable)getMaterialImageWithPath:(NSString * _Nonnull)path SWIFT_WARN_UNUSED_RESULT;
+ (void)saveMaterialImage:(UIImage * _Nonnull)image key:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, CategoryType, open) {
  CategoryTypeArchitecture = 0,
  CategoryTypeProduct = 1,
  CategoryTypeFinishes = 2,
  CategoryTypeMigrations = 3,
  CategoryTypeSpatial = 4,
};

typedef SWIFT_ENUM(NSInteger, InteriorStyle, open) {
  InteriorStyleCasual = 0,
  InteriorStyleClassic = 1,
  InteriorStyleModern = 2,
  InteriorStyleNatural = 3,
  InteriorStyleNordic = 4,
  InteriorStyleRomantic = 5,
  InteriorStyleVintage = 6,
};


@class NSDictionary;

SWIFT_CLASS("_TtC6UBGear15SpaceClassifier")
@interface SpaceClassifier : NSObject
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic) CGFloat percent;
- (nonnull instancetype)initWith:(NSDictionary * _Nonnull)result OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nonnull)percentToString SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC6UBGear10SpaceColor")
@interface SpaceColor : NSObject
@property (nonatomic) CGFloat red;
@property (nonatomic) CGFloat green;
@property (nonatomic) CGFloat blue;
@property (nonatomic) double percent;
- (nonnull instancetype)initWith:(NSDictionary * _Nonnull)result OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC6UBGear20SpaceObjectDetection")
@interface SpaceObjectDetection : NSObject
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic) CGFloat percent;
@property (nonatomic) CGRect rect;
- (nonnull instancetype)initWith:(NSDictionary * _Nonnull)result OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nonnull)percentToString SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC6UBGear10SpaceStyle")
@interface SpaceStyle : NSObject
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic) CGFloat percent;
@property (nonatomic, copy) NSString * _Nonnull styleDescription;
- (nonnull instancetype)initWith:(NSDictionary * _Nonnull)result OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nonnull)percentToString SWIFT_WARN_UNUSED_RESULT;
@end

@class UBLikeInfo;

SWIFT_PROTOCOL("_TtP6UBGear14UBLikeProtocol_") SWIFT_AVAILABILITY(ios,introduced=11.3)
@protocol UBLikeProtocol
@property (nonatomic, strong) UBLikeInfo * _Nullable likeInfo;
- (void)setLikeInformationWith:(UBLikeInfo * _Nonnull)like;
@end

@class UBStyle;

/// A informative class that manages properties of figure.
SWIFT_CLASS("_TtC6UBGear7UBAsset") SWIFT_AVAILABILITY(ios,introduced=11.3)
@interface UBAsset : NSObject <UBLikeProtocol>
@property (nonatomic, strong) UBLikeInfo * _Nullable likeInfo;
/// The <code>UUID</code> of <code>UBAsset</code>
@property (nonatomic, readonly, copy) NSString * _Nonnull asset_id;
@property (nonatomic, readonly, copy) NSString * _Nonnull title;
/// A brand name of asset
@property (nonatomic, readonly, copy) NSString * _Nonnull brand;
@property (nonatomic, readonly, copy) NSString * _Nonnull thumbnail_path;
/// A <code>Boolean</code> value indicating whether the user likes it.
@property (nonatomic) BOOL isLike;
/// An array of <code>UBStyle</code>
@property (nonatomic, copy) NSArray<UBStyle *> * _Nonnull styles;
@property (nonatomic, readonly, copy) NSString * _Nonnull asset_description;
- (void)setLikeInformationWith:(UBLikeInfo * _Nonnull)like;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// A informative class that represents the figure’s apperance.
SWIFT_CLASS("_TtCC6UBGear7UBAsset7UBStyle")
@interface UBStyle : NSObject
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nonnull asset_id;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic) BOOL enabled;
@property (nonatomic) BOOL is_default;
@property (nonatomic, copy) NSString * _Nonnull thumbnail_path;
@property (nonatomic, copy) NSDate * _Nonnull created_date;
@property (nonatomic, copy) NSDate * _Nonnull updated_date;
@property (nonatomic, copy) NSDate * _Nonnull deleted_date;
/// A  <code>URL</code> path of color chip image
@property (nonatomic, copy) NSString * _Nonnull color_chip_path;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC6UBGear10UBAssetSet") SWIFT_AVAILABILITY(ios,introduced=11.3)
@interface UBAssetSet : NSObject
@property (nonatomic, copy) NSString * _Nonnull title;
@property (nonatomic) BOOL enabled;
@property (nonatomic) BOOL publish;
@property (nonatomic, copy) NSString * _Nonnull thumbnail_path;
@property (nonatomic, copy) NSArray<UBAsset *> * _Nonnull assets;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UBResponse;
@class UIViewController;

SWIFT_CLASS("_TtC6UBGear6UBAuth") SWIFT_AVAILABILITY(ios,introduced=11.3)
@interface UBAuth : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable currentToken;
- (void)configureWithCliendId:(NSString * _Nonnull)cliendId clientSecret:(NSString * _Nonnull)clientSecret poolId:(NSString * _Nonnull)poolId webDomain:(NSString * _Nonnull)webDomain appscheme:(NSString * _Nonnull)appscheme;
- (void)updateCurrentUser;
- (void)signInEmail:(NSString * _Nonnull)email password:(NSString * _Nonnull)password completion:(void (^ _Nonnull)(UBResponse * _Nonnull))completion;
- (void)signOut;
/// 회원 탈퇴하기
- (void)leaveWithUserId:(NSString * _Nonnull)userId completion:(void (^ _Nonnull)(UBResponse * _Nonnull))completion;
- (void)changePasswordWithCurrent:(NSString * _Nonnull)current new:(NSString * _Nonnull)new_ completion:(void (^ _Nonnull)(UBResponse * _Nonnull))completion;
- (void)forgotPasswordWithUserName:(NSString * _Nonnull)userName completion:(void (^ _Nonnull)(UBResponse * _Nonnull))completion;
- (void)resendConfirmationLinkWithUserName:(NSString * _Nonnull)userName completion:(void (^ _Nonnull)(UBResponse * _Nonnull))completion;
- (BOOL)isLoggedIn SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isSignedInCognito SWIFT_WARN_UNUSED_RESULT;
- (void)startSignInFlowWithViewController:(UIViewController * _Nonnull)viewController;
- (BOOL)isValidEmail:(NSString * _Nonnull)email SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isValidPassword:(NSString * _Nonnull)password SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol AWSCognitoIdentityPasswordAuthentication;

SWIFT_AVAILABILITY(ios,introduced=11.3)
@interface UBAuth (SWIFT_EXTENSION(UBGear)) <AWSCognitoIdentityInteractiveAuthenticationDelegate>
- (id <AWSCognitoIdentityPasswordAuthentication> _Nonnull)startPasswordAuthentication SWIFT_WARN_UNUSED_RESULT;
@end

@class AWSCognitoIdentityPasswordAuthenticationInput;
@class AWSCognitoIdentityPasswordAuthenticationDetails;

SWIFT_AVAILABILITY(ios,introduced=11.3)
@interface UBAuth (SWIFT_EXTENSION(UBGear)) <AWSCognitoIdentityPasswordAuthentication>
- (void)getPasswordAuthenticationDetails:(AWSCognitoIdentityPasswordAuthenticationInput * _Nonnull)authenticationInput passwordAuthenticationCompletionSource:(AWSTaskCompletionSource<AWSCognitoIdentityPasswordAuthenticationDetails *> * _Nonnull)passwordAuthenticationCompletionSource;
- (void)didCompletePasswordAuthenticationStepWithError:(NSError * _Nullable)error;
@end

@class UBMaterial;

SWIFT_CLASS("_TtC6UBGear10UBCategory") SWIFT_AVAILABILITY(ios,introduced=11.3)
@interface UBCategory : NSObject
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic) BOOL is_default;
@property (nonatomic) BOOL enabled;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull thumbnail_path;
@property (nonatomic, copy) NSString * _Nonnull parent_id;
@property (nonatomic, copy) NSString * _Nonnull path;
@property (nonatomic) NSInteger depth;
@property (nonatomic) NSInteger sort;
@property (nonatomic, copy) NSString * _Nonnull code;
@property (nonatomic, copy) NSArray<UBCategory *> * _Nonnull subcategories;
@property (nonatomic) BOOL is_endpoint;
@property (nonatomic, copy) NSArray<UBAsset *> * _Nonnull assets;
@property (nonatomic, copy) NSString * _Nonnull english;
@property (nonatomic, copy) NSString * _Nonnull korean;
@property (nonatomic, copy) NSString * _Nonnull japanese;
- (nonnull instancetype)initWithResponse:(NSDictionary * _Nonnull)response OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWith:(NSString * _Nonnull)jsonString OBJC_DESIGNATED_INITIALIZER;
+ (void)requestCategoriesWithType:(enum CategoryType)type completion:(void (^ _Nonnull)(UBResponse * _Nonnull, UBCategory * _Nullable))completion;
+ (void)requestSearchCategoryWithCompletion:(void (^ _Nonnull)(UBResponse * _Nonnull, NSArray<UBCategory *> * _Nullable))completion;
+ (void)requestFlattendCategoriesWithType:(enum CategoryType)type completion:(void (^ _Nonnull)(UBResponse * _Nonnull, NSArray<UBCategory *> * _Nullable))completion;
+ (void)requestMaterialsWithCategory:(UBCategory * _Nonnull)category limit:(NSInteger)limit offset:(NSInteger)offset userEmail:(NSString * _Nonnull)userEmail completion:(void (^ _Nonnull)(UBResponse * _Nonnull, NSArray<UBMaterial *> * _Nullable))completion;
+ (void)requestAutoCompletionWithKeyword:(NSString * _Nonnull)keyword count:(NSInteger)count completion:(void (^ _Nonnull)(UBResponse * _Nonnull, NSArray<UBCategory *> * _Nullable))completion;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC6UBGear10UBLikeInfo") SWIFT_AVAILABILITY(ios,introduced=11.3)
@interface UBLikeInfo : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC6UBGear10UBMaterial") SWIFT_AVAILABILITY(ios,introduced=11.3)
@interface UBMaterial : NSObject <UBLikeProtocol>
@property (nonatomic, copy) NSString * _Nonnull geometry;
@property (nonatomic, copy) NSString * _Nonnull material_id;
@property (nonatomic, copy) NSString * _Nonnull thumbnail_path;
@property (nonatomic, strong) NSDictionary * _Nonnull responseData;
@property (nonatomic, copy) NSString * _Nonnull title;
@property (nonatomic, copy) NSString * _Nonnull materialDescription;
@property (nonatomic, readonly, copy) NSString * _Nonnull brand;
@property (nonatomic, strong) UBLikeInfo * _Nullable likeInfo;
@property (nonatomic) BOOL isLike;
- (nonnull instancetype)initWith:(NSDictionary * _Nonnull)response OBJC_DESIGNATED_INITIALIZER;
- (void)setLikeInformationWith:(UBLikeInfo * _Nonnull)like;
+ (void)requestMaterialDetailWithMaterialId:(NSString * _Nonnull)materialId userEmail:(NSString * _Nonnull)userEmail completion:(void (^ _Nonnull)(UBResponse * _Nonnull, UBMaterial * _Nullable))completion;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC6UBGear10UBResponse")
@interface UBResponse : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable result;
@property (nonatomic, readonly, strong) NSDictionary * _Nullable responseData;
@property (nonatomic, readonly, copy) NSString * _Nullable message;
- (nonnull instancetype)initWithResponseObject:(id _Nonnull)responseObject OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithError:(NSError * _Nonnull)error OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithResult:(NSString * _Nonnull)result message:(NSString * _Nonnull)message data:(NSDictionary * _Nullable)data OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface UBResponse (SWIFT_EXTENSION(UBGear))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UBResponse * _Nonnull success;)
+ (UBResponse * _Nonnull)success SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) BOOL isSuccess;
@end


SWIFT_CLASS("_TtC6UBGear13UBSpaceResult") SWIFT_AVAILABILITY(ios,introduced=11.3)
@interface UBSpaceResult : NSObject <UBLikeProtocol>
@property (nonatomic, strong) NSDictionary * _Nonnull data;
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, copy) NSString * _Nonnull user_id;
@property (nonatomic, copy) NSDate * _Nullable createDate;
@property (nonatomic, copy) NSDate * _Nullable deletedDate;
@property (nonatomic, copy) NSString * _Nonnull title;
@property (nonatomic) BOOL isPublic;
@property (nonatomic, copy) NSString * _Nonnull image_path;
@property (nonatomic) CGSize image_size;
@property (nonatomic, copy) NSString * _Nonnull profile;
@property (nonatomic, copy) NSString * _Nonnull username;
@property (nonatomic, copy) NSArray<SpaceClassifier *> * _Nonnull classifier_result;
@property (nonatomic, copy) NSArray<SpaceObjectDetection *> * _Nonnull detector_result;
@property (nonatomic, copy) NSArray<SpaceStyle *> * _Nonnull style_result;
@property (nonatomic, copy) NSArray<SpaceColor *> * _Nonnull color_result;
@property (nonatomic, readonly, strong) SpaceClassifier * _Nonnull mainRoomType;
@property (nonatomic, readonly, strong) SpaceStyle * _Nonnull mainStyle;
@property (nonatomic, strong) UBLikeInfo * _Nullable likeInfo;
@property (nonatomic) BOOL isLike;
@property (nonatomic, readonly) BOOL isDeleted;
- (nonnull instancetype)initWith:(NSDictionary * _Nonnull)data OBJC_DESIGNATED_INITIALIZER;
- (void)setLikeInformationWith:(UBLikeInfo * _Nonnull)like;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__ARM_ARCH_7A__) && __ARM_ARCH_7A__
// Generated by Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)
#ifndef UBGEAR_SWIFT_H
#define UBGEAR_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AWSCognitoIdentityProvider;
@import AWSCore;
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="UBGear",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif


@class NSNumber;
@class NSURL;
@class NSString;
@class NSDate;
@class NSData;
@class UIImage;

SWIFT_CLASS("_TtC6UBGear12CacheManager")
@interface CacheManager : NSObject
+ (void)executeManagingStroage;
+ (double)sizeOfCachedStorage SWIFT_WARN_UNUSED_RESULT;
+ (NSURL * _Nullable)oldestAsset SWIFT_WARN_UNUSED_RESULT;
+ (NSURL * _Nullable)findFigureWithUuid:(NSString * _Nonnull)uuid updateDate:(NSDate * _Nullable)updateDate SWIFT_WARN_UNUSED_RESULT;
+ (void)storeItemAsDaeiWithUuid:(NSString * _Nonnull)uuid data:(NSData * _Nonnull)data eTag:(NSString * _Nonnull)eTag completion:(SWIFT_NOESCAPE void (^ _Nonnull)(BOOL, NSError * _Nullable))completion;
+ (void)createCacheDirectoryIfNeeded;
+ (void)deleteDirectoryIfNeededWithDirectory:(NSURL * _Nonnull)directory;
+ (void)deleteOldestItemWithCompletion:(void (^ _Nullable)(BOOL, NSString * _Nonnull))completion;
+ (void)deleteItemAt:(NSURL * _Nonnull)url completion:(SWIFT_NOESCAPE void (^ _Nonnull)(BOOL, NSString * _Nonnull))completion;
+ (void)deleteItemWithUuid:(NSString * _Nonnull)uuid completion:(SWIFT_NOESCAPE void (^ _Nonnull)(BOOL, NSString * _Nonnull))completion;
+ (void)deleteAllItemWithCompletion:(SWIFT_NOESCAPE void (^ _Nonnull)(BOOL, NSString * _Nonnull))completion;
+ (UIImage * _Nullable)getMaterialImageWithPath:(NSString * _Nonnull)path SWIFT_WARN_UNUSED_RESULT;
+ (void)saveMaterialImage:(UIImage * _Nonnull)image key:(NSString * _Nonnull)key;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, CategoryType, open) {
  CategoryTypeArchitecture = 0,
  CategoryTypeProduct = 1,
  CategoryTypeFinishes = 2,
  CategoryTypeMigrations = 3,
  CategoryTypeSpatial = 4,
};

typedef SWIFT_ENUM(NSInteger, InteriorStyle, open) {
  InteriorStyleCasual = 0,
  InteriorStyleClassic = 1,
  InteriorStyleModern = 2,
  InteriorStyleNatural = 3,
  InteriorStyleNordic = 4,
  InteriorStyleRomantic = 5,
  InteriorStyleVintage = 6,
};


@class NSDictionary;

SWIFT_CLASS("_TtC6UBGear15SpaceClassifier")
@interface SpaceClassifier : NSObject
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic) CGFloat percent;
- (nonnull instancetype)initWith:(NSDictionary * _Nonnull)result OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nonnull)percentToString SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC6UBGear10SpaceColor")
@interface SpaceColor : NSObject
@property (nonatomic) CGFloat red;
@property (nonatomic) CGFloat green;
@property (nonatomic) CGFloat blue;
@property (nonatomic) double percent;
- (nonnull instancetype)initWith:(NSDictionary * _Nonnull)result OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC6UBGear20SpaceObjectDetection")
@interface SpaceObjectDetection : NSObject
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic) CGFloat percent;
@property (nonatomic) CGRect rect;
- (nonnull instancetype)initWith:(NSDictionary * _Nonnull)result OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nonnull)percentToString SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC6UBGear10SpaceStyle")
@interface SpaceStyle : NSObject
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic) CGFloat percent;
@property (nonatomic, copy) NSString * _Nonnull styleDescription;
- (nonnull instancetype)initWith:(NSDictionary * _Nonnull)result OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nonnull)percentToString SWIFT_WARN_UNUSED_RESULT;
@end

@class UBLikeInfo;

SWIFT_PROTOCOL("_TtP6UBGear14UBLikeProtocol_") SWIFT_AVAILABILITY(ios,introduced=11.3)
@protocol UBLikeProtocol
@property (nonatomic, strong) UBLikeInfo * _Nullable likeInfo;
- (void)setLikeInformationWith:(UBLikeInfo * _Nonnull)like;
@end

@class UBStyle;

/// A informative class that manages properties of figure.
SWIFT_CLASS("_TtC6UBGear7UBAsset") SWIFT_AVAILABILITY(ios,introduced=11.3)
@interface UBAsset : NSObject <UBLikeProtocol>
@property (nonatomic, strong) UBLikeInfo * _Nullable likeInfo;
/// The <code>UUID</code> of <code>UBAsset</code>
@property (nonatomic, readonly, copy) NSString * _Nonnull asset_id;
@property (nonatomic, readonly, copy) NSString * _Nonnull title;
/// A brand name of asset
@property (nonatomic, readonly, copy) NSString * _Nonnull brand;
@property (nonatomic, readonly, copy) NSString * _Nonnull thumbnail_path;
/// A <code>Boolean</code> value indicating whether the user likes it.
@property (nonatomic) BOOL isLike;
/// An array of <code>UBStyle</code>
@property (nonatomic, copy) NSArray<UBStyle *> * _Nonnull styles;
@property (nonatomic, readonly, copy) NSString * _Nonnull asset_description;
- (void)setLikeInformationWith:(UBLikeInfo * _Nonnull)like;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// A informative class that represents the figure’s apperance.
SWIFT_CLASS("_TtCC6UBGear7UBAsset7UBStyle")
@interface UBStyle : NSObject
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nonnull asset_id;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic) BOOL enabled;
@property (nonatomic) BOOL is_default;
@property (nonatomic, copy) NSString * _Nonnull thumbnail_path;
@property (nonatomic, copy) NSDate * _Nonnull created_date;
@property (nonatomic, copy) NSDate * _Nonnull updated_date;
@property (nonatomic, copy) NSDate * _Nonnull deleted_date;
/// A  <code>URL</code> path of color chip image
@property (nonatomic, copy) NSString * _Nonnull color_chip_path;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC6UBGear10UBAssetSet") SWIFT_AVAILABILITY(ios,introduced=11.3)
@interface UBAssetSet : NSObject
@property (nonatomic, copy) NSString * _Nonnull title;
@property (nonatomic) BOOL enabled;
@property (nonatomic) BOOL publish;
@property (nonatomic, copy) NSString * _Nonnull thumbnail_path;
@property (nonatomic, copy) NSArray<UBAsset *> * _Nonnull assets;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class UBResponse;
@class UIViewController;

SWIFT_CLASS("_TtC6UBGear6UBAuth") SWIFT_AVAILABILITY(ios,introduced=11.3)
@interface UBAuth : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable currentToken;
- (void)configureWithCliendId:(NSString * _Nonnull)cliendId clientSecret:(NSString * _Nonnull)clientSecret poolId:(NSString * _Nonnull)poolId webDomain:(NSString * _Nonnull)webDomain appscheme:(NSString * _Nonnull)appscheme;
- (void)updateCurrentUser;
- (void)signInEmail:(NSString * _Nonnull)email password:(NSString * _Nonnull)password completion:(void (^ _Nonnull)(UBResponse * _Nonnull))completion;
- (void)signOut;
/// 회원 탈퇴하기
- (void)leaveWithUserId:(NSString * _Nonnull)userId completion:(void (^ _Nonnull)(UBResponse * _Nonnull))completion;
- (void)changePasswordWithCurrent:(NSString * _Nonnull)current new:(NSString * _Nonnull)new_ completion:(void (^ _Nonnull)(UBResponse * _Nonnull))completion;
- (void)forgotPasswordWithUserName:(NSString * _Nonnull)userName completion:(void (^ _Nonnull)(UBResponse * _Nonnull))completion;
- (void)resendConfirmationLinkWithUserName:(NSString * _Nonnull)userName completion:(void (^ _Nonnull)(UBResponse * _Nonnull))completion;
- (BOOL)isLoggedIn SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isSignedInCognito SWIFT_WARN_UNUSED_RESULT;
- (void)startSignInFlowWithViewController:(UIViewController * _Nonnull)viewController;
- (BOOL)isValidEmail:(NSString * _Nonnull)email SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isValidPassword:(NSString * _Nonnull)password SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol AWSCognitoIdentityPasswordAuthentication;

SWIFT_AVAILABILITY(ios,introduced=11.3)
@interface UBAuth (SWIFT_EXTENSION(UBGear)) <AWSCognitoIdentityInteractiveAuthenticationDelegate>
- (id <AWSCognitoIdentityPasswordAuthentication> _Nonnull)startPasswordAuthentication SWIFT_WARN_UNUSED_RESULT;
@end

@class AWSCognitoIdentityPasswordAuthenticationInput;
@class AWSCognitoIdentityPasswordAuthenticationDetails;

SWIFT_AVAILABILITY(ios,introduced=11.3)
@interface UBAuth (SWIFT_EXTENSION(UBGear)) <AWSCognitoIdentityPasswordAuthentication>
- (void)getPasswordAuthenticationDetails:(AWSCognitoIdentityPasswordAuthenticationInput * _Nonnull)authenticationInput passwordAuthenticationCompletionSource:(AWSTaskCompletionSource<AWSCognitoIdentityPasswordAuthenticationDetails *> * _Nonnull)passwordAuthenticationCompletionSource;
- (void)didCompletePasswordAuthenticationStepWithError:(NSError * _Nullable)error;
@end

@class UBMaterial;

SWIFT_CLASS("_TtC6UBGear10UBCategory") SWIFT_AVAILABILITY(ios,introduced=11.3)
@interface UBCategory : NSObject
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic) BOOL is_default;
@property (nonatomic) BOOL enabled;
@property (nonatomic, copy) NSString * _Nonnull name;
@property (nonatomic, copy) NSString * _Nonnull thumbnail_path;
@property (nonatomic, copy) NSString * _Nonnull parent_id;
@property (nonatomic, copy) NSString * _Nonnull path;
@property (nonatomic) NSInteger depth;
@property (nonatomic) NSInteger sort;
@property (nonatomic, copy) NSString * _Nonnull code;
@property (nonatomic, copy) NSArray<UBCategory *> * _Nonnull subcategories;
@property (nonatomic) BOOL is_endpoint;
@property (nonatomic, copy) NSArray<UBAsset *> * _Nonnull assets;
@property (nonatomic, copy) NSString * _Nonnull english;
@property (nonatomic, copy) NSString * _Nonnull korean;
@property (nonatomic, copy) NSString * _Nonnull japanese;
- (nonnull instancetype)initWithResponse:(NSDictionary * _Nonnull)response OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWith:(NSString * _Nonnull)jsonString OBJC_DESIGNATED_INITIALIZER;
+ (void)requestCategoriesWithType:(enum CategoryType)type completion:(void (^ _Nonnull)(UBResponse * _Nonnull, UBCategory * _Nullable))completion;
+ (void)requestSearchCategoryWithCompletion:(void (^ _Nonnull)(UBResponse * _Nonnull, NSArray<UBCategory *> * _Nullable))completion;
+ (void)requestFlattendCategoriesWithType:(enum CategoryType)type completion:(void (^ _Nonnull)(UBResponse * _Nonnull, NSArray<UBCategory *> * _Nullable))completion;
+ (void)requestMaterialsWithCategory:(UBCategory * _Nonnull)category limit:(NSInteger)limit offset:(NSInteger)offset userEmail:(NSString * _Nonnull)userEmail completion:(void (^ _Nonnull)(UBResponse * _Nonnull, NSArray<UBMaterial *> * _Nullable))completion;
+ (void)requestAutoCompletionWithKeyword:(NSString * _Nonnull)keyword count:(NSInteger)count completion:(void (^ _Nonnull)(UBResponse * _Nonnull, NSArray<UBCategory *> * _Nullable))completion;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC6UBGear10UBLikeInfo") SWIFT_AVAILABILITY(ios,introduced=11.3)
@interface UBLikeInfo : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC6UBGear10UBMaterial") SWIFT_AVAILABILITY(ios,introduced=11.3)
@interface UBMaterial : NSObject <UBLikeProtocol>
@property (nonatomic, copy) NSString * _Nonnull geometry;
@property (nonatomic, copy) NSString * _Nonnull material_id;
@property (nonatomic, copy) NSString * _Nonnull thumbnail_path;
@property (nonatomic, strong) NSDictionary * _Nonnull responseData;
@property (nonatomic, copy) NSString * _Nonnull title;
@property (nonatomic, copy) NSString * _Nonnull materialDescription;
@property (nonatomic, readonly, copy) NSString * _Nonnull brand;
@property (nonatomic, strong) UBLikeInfo * _Nullable likeInfo;
@property (nonatomic) BOOL isLike;
- (nonnull instancetype)initWith:(NSDictionary * _Nonnull)response OBJC_DESIGNATED_INITIALIZER;
- (void)setLikeInformationWith:(UBLikeInfo * _Nonnull)like;
+ (void)requestMaterialDetailWithMaterialId:(NSString * _Nonnull)materialId userEmail:(NSString * _Nonnull)userEmail completion:(void (^ _Nonnull)(UBResponse * _Nonnull, UBMaterial * _Nullable))completion;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC6UBGear10UBResponse")
@interface UBResponse : NSObject
@property (nonatomic, readonly, copy) NSString * _Nullable result;
@property (nonatomic, readonly, strong) NSDictionary * _Nullable responseData;
@property (nonatomic, readonly, copy) NSString * _Nullable message;
- (nonnull instancetype)initWithResponseObject:(id _Nonnull)responseObject OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithError:(NSError * _Nonnull)error OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithResult:(NSString * _Nonnull)result message:(NSString * _Nonnull)message data:(NSDictionary * _Nullable)data OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@interface UBResponse (SWIFT_EXTENSION(UBGear))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) UBResponse * _Nonnull success;)
+ (UBResponse * _Nonnull)success SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) BOOL isSuccess;
@end


SWIFT_CLASS("_TtC6UBGear13UBSpaceResult") SWIFT_AVAILABILITY(ios,introduced=11.3)
@interface UBSpaceResult : NSObject <UBLikeProtocol>
@property (nonatomic, strong) NSDictionary * _Nonnull data;
@property (nonatomic, copy) NSString * _Nonnull id;
@property (nonatomic, copy) NSString * _Nonnull uuid;
@property (nonatomic, copy) NSString * _Nonnull user_id;
@property (nonatomic, copy) NSDate * _Nullable createDate;
@property (nonatomic, copy) NSDate * _Nullable deletedDate;
@property (nonatomic, copy) NSString * _Nonnull title;
@property (nonatomic) BOOL isPublic;
@property (nonatomic, copy) NSString * _Nonnull image_path;
@property (nonatomic) CGSize image_size;
@property (nonatomic, copy) NSString * _Nonnull profile;
@property (nonatomic, copy) NSString * _Nonnull username;
@property (nonatomic, copy) NSArray<SpaceClassifier *> * _Nonnull classifier_result;
@property (nonatomic, copy) NSArray<SpaceObjectDetection *> * _Nonnull detector_result;
@property (nonatomic, copy) NSArray<SpaceStyle *> * _Nonnull style_result;
@property (nonatomic, copy) NSArray<SpaceColor *> * _Nonnull color_result;
@property (nonatomic, readonly, strong) SpaceClassifier * _Nonnull mainRoomType;
@property (nonatomic, readonly, strong) SpaceStyle * _Nonnull mainStyle;
@property (nonatomic, strong) UBLikeInfo * _Nullable likeInfo;
@property (nonatomic) BOOL isLike;
@property (nonatomic, readonly) BOOL isDeleted;
- (nonnull instancetype)initWith:(NSDictionary * _Nonnull)data OBJC_DESIGNATED_INITIALIZER;
- (void)setLikeInformationWith:(UBLikeInfo * _Nonnull)like;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#endif
